class DataError(RuntimeError):
    ROBOT_EXIT_ON_FAILURE = True
